syntax = "proto3";
package agent.v1;

option go_package = "github.com/nesaorg/nesachain/x/agent/types";

import "gogoproto/gogo.proto";
import "amino/amino.proto";
import "cosmos_proto/cosmos.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "cosmos/base/v1beta1/coin.proto";

// Params defines the agent module's global params.
message Params {
  option (amino.name) = "agent/params";

  // The minimum coins that needs to be locked when user registers a session
  cosmos.base.v1beta1.Coin user_minimum_lock = 1
      [ (gogoproto.nullable) = false ];

  // When the session is created, the time period that inference agent can
  // submit payment. After this period, the session will be automatically
  // canceled.
  google.protobuf.Duration session_time = 2
      [ (gogoproto.nullable) = false, (gogoproto.stdduration) = true ];
  // Global vrf seed. Each user calculates their own vrf seed based on the
  // global vrf seed when vrf is initialized.
  bytes global_seed = 3;
  // The minimum version number for agent registration/update,
  // registration/update is not allowed if the version number is lower than this
  // one
  uint64 lowest_agent_version = 4;
  // The highest version number of agent registration/update,
  // registration/update is not allowed if the version number is higher than
  // this
  uint64 highest_agent_version = 5;
  // The number of validators during the challenge.
  // When the number of agents with corresponding models is lower than this
  // number, the challenge will not be triggered.
  uint64 validator_count = 6;
  // The time an agent is valid on the chain after registration/update.
  // After this time is exceeded, the agent will be automatically marked as
  // invalid.
  google.protobuf.Duration agent_valid_time = 7
      [ (gogoproto.nullable) = false, (gogoproto.stdduration) = true ];
  // The admin account of the agent module
  string admin = 8 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
}

// InnerValues defines the values that changed by agent module.
message InnerValues {
  // The seed used by the module for VRF. It changes with each block and each
  // usage.
  bytes seed = 1;
}

// AgentStatus enumerates the inference agent status.
enum AgentStatus {
  // AGENT_STATUS_ACTIVE represents the active status.
  AGENT_STATUS_ACTIVE = 0;
  // AGENT_STATUS_INACTIVE represents the inactive status.
  AGENT_STATUS_INACTIVE = 1;
}

// The inference agent represents the registered entity on the chain that
// provides the inference service.
message InferenceAgent {
  // The on-chain address of the inference agent
  string account = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // URL address that provides the inference service.
  string url = 2 [ (gogoproto.customname) = "URL" ];
  // The version of the inference agent.
  uint64 version = 3;
  // The status of the inference agent.
  AgentStatus status = 4;
  // The timestamp that agent becomes inactive.
  google.protobuf.Timestamp valid_until = 5
      [ (gogoproto.stdtime) = true, (gogoproto.nullable) = false ];
}

// TokenPrice defines the price of the token used for payment.
message TokenPrice {
  cosmos.base.v1beta1.Coin input_price = 1 [ (gogoproto.nullable) = false ];
  cosmos.base.v1beta1.Coin output_price = 2 [ (gogoproto.nullable) = false ];
}

// SessionStatus enumerates the statuses of a session.
enum SessionStatus {
  // SESSION_STATUS_DEFAULT is a placeholder and will not appear in session.
  SESSION_STATUS_DEFAULT = 0;
  // SESSION_STATUS_PENDING indicates the session is pending. It's waiting for
  // the payment to be submitted.
  SESSION_STATUS_PENDING = 1;
  // SESSION_STATUS_SUBMITTED indicates the payment has been submitted.
  SESSION_STATUS_SUBMITTED = 2;
}

// Session represents an inference session.
message Session {
  // The ID of the session. It's compressed secp256k1 pubkey.
  string session_id = 1;
  // The account of the user who created and pay for the session.
  string account = 2 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // The name of the model used in the session
  string model_name = 3;
  // The account of the agent providing the model's inference service.
  string agent_account = 4 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // The amount of coins locked by the user to do inference.
  cosmos.base.v1beta1.Coin user_lock = 5 [ (gogoproto.nullable) = false ];
  // the price of each token in session.
  TokenPrice token_price = 6 [ (gogoproto.nullable) = false ];
  // The expiration timestamp of the session.
  google.protobuf.Timestamp expiration_at = 7
      [ (gogoproto.stdtime) = true, (gogoproto.nullable) = false ];
  // The status of the session.
  SessionStatus status = 8;
  // The remaining available tokens for the user.
  cosmos.base.v1beta1.Coin available_lock = 9 [ (gogoproto.nullable) = false ];
}

// VrfSeed represents the VRF seed for each user.
message VrfSeed {
  // The account of the user.
  string account = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  // The VRF seed for the user.
  bytes seed = 2;
}
